### ISSUE TITLE
Block: Setup Azure DevOps project

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/hangar#1]
As someone setting up the project infrastructure, I want to have a detailed guide on how to activate and prepare Azure DevOps so that I can get this done fast and without errors.

Detail requisites for cases where Azure DevOps is provided.

**Comment by prathibhapadma** [comment]
Document completed for Practical guide to activate and prepare Azure DevOps, It is under review.

**Comment by prathibhapadma** [comment]
According to guidelines had few changes and created pull request.
