### ISSUE TITLE
Block: Provision EKS environment pipeline

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/hangar#10]
As someone setting up the project infrastructure, I want to have a detailed guide on how to provision the environment from Azure DevOps so that I can get this done fast and without errors.

Tasks:
- Create K8s cluster
- Create LB
- ...

Using Terraform. Provide some basic guidance on how to use it but keep in mind that it will be primarily executed from the pipeline. Explain the highlights of the deployed environment.

Make pipeline parametrized for deploying several environments.

Evaluate Rancher

**Comment by isandesh1986** [comment]
@albertdb - Hi Albert, could you also clarify on what exactly needs to be provisioned in the tasks. The title mentions about EKS, but the Tasks section in the description also mentions about the DB. Could you please clarify the same.

**Comment by albertdb** [comment]
Sorry, that was a typo, it meant LB, as an example. Basically, whatever is needed for having a landing zone for deploying then the quarkus reference application. By the way, if the application needs a DB, that would also be part of setting up the environment. We are aiming to have a cloud-native solution, so we prefer managed solutions, so in that particular case that would be an AWS RDS database.

**Comment by isandesh1986** [comment]
> Sorry, that was a typo, it meant LB, as an example. Basically, whatever is needed for having a landing zone for deploying then the quarkus reference application. By the way, if the application needs a DB, that would also be part of setting up the environment. We are aiming to have a cloud-native solution, so we prefer managed solutions, so in that particular case that would be an AWS RDS database, not deploying a DB inside the cluster.

Great, Thank you
