### ISSUE TITLE
Create Build pipeline definition and assets for Google Cloud

### ISSUE THREAD

**Issue by lpinon** [devonfw/hangar#195]
REQUIREMENTS

- [ ] Be compliant with Hangar way of working.

SUBTASKS

- [x] #259 
- [x] Quarkus
- [x] Angular

- [x] #264 
- [x] #265

**Comment by ultymatom** [comment]
Cuando ha sido hecho para node, ha sido hecho para angular

**Comment by mtarnove** [comment]
falta docu
