### ISSUE TITLE
Automate creation of a system account, validate and assign roles in Google Cloud

### ISSUE THREAD

**Issue by lpinon** [devonfw/hangar#208]
REQUIREMENTS

- [ ] Be compliant with Hangar way of working.

**Comment by mtarnove** [comment]
=Service account, give permissions to a user to work with it

**Comment by mcerverc** [comment]
To create a project, you must have the resourcemanager.projects.create permission. 
This permission is included in roles like the Project Creator role (roles/resourcemanager.projectCreator)

**Comment by abcarcol** [comment]
**GCP IAM overview**

- _Permissions_
Permissions determine what operations are allowed on a resource. In the IAM world, permissions are represented in the form of **_service.resource.verb_**

- _Roles_ 
A role is a collection of permissions. You cannot grant a permission to the user directly. Instead, you grant them a role. When you grant a role to a user, you grant them all the permissions that the role contains.
![Image](https://user-images.githubusercontent.com/1241379/191428376-a7ce02fc-8d65-4f49-8c38-d8c80e163bad.png). There are three kinds of roles: _Basic roles, Predefined roles and Custom roles_. Custom roles help you enforce the principle of least privilege [https://cloud.google.com/iam/docs/using-iam-securely#least_privilege](url)

- _Allow policy (Collection of bindings)_
An allow policy consists of a list of role bindings. A role binding binds a list of principals to a role.
![Image](https://user-images.githubusercontent.com/1241379/191428593-d4e6c177-a3e0-4a63-ad1d-4ecd19d0b673.png)

- _GCP Resource hierarchy_
![Image](https://user-images.githubusercontent.com/1241379/191427226-6c607d56-3a76-4c0f-9a25-8ac40813ec61.png)
Resources inherit the allow policies of all of their parent resources. The effective allow policy for a resource is the union of the allow policy set on that resource and the allow policies inherited from higher up in the hierarchy.

**Discussion**

1. What is the folder that contains the project and, in turn, the organization that contains that folder?
2. Reviewing a permission requires examining the whole resource hierarchy.
3. Permissions desirable for the demo on 28/09/2022.

**Comment by abcarcol** [comment]
Differences between AWS and GCP (Hangar related)

1. In create-user.sh and verify-account-policies.sh, there are no admin credentials in GCP. 
2. The admin user will be the one that logs in with the script _INTERACTIVELY_.
3. verify-account-policies.sh requires the project id as an argument.

**Comment by mcerverc** [comment]
Permission required to create a repo: source.repos.create

**Comment by mtarnove** [comment]
Status 06.10 - Abel has to revise BOT comments ASAP so that Albert could review it. @abcarcol
