### ISSUE TITLE
Automate setup of logging and monitoring for Google CloudRun

### ISSUE THREAD

**Issue by lpinon** [devonfw/hangar#215]
TASKS

- [ ] [SPIKE] Evaluate Google Cloud offering.

**Comment by lpinon** [comment]
@ultymatom  check this tools:

**Operations-Focused Tools:**

- Cloud Monitoring
- Cloud Logging
- Error Reporting
- Service Monitoring

**Application Performance Management Tools:**

- Cloud Debugger
- Cloud Trace
- Cloud Profiler

**Comment by ultymatom** [comment]
Cloud monitoring:
    We can create some templates (json file) of dashboard for cloud run

**Comment by ultymatom** [comment]
Cloud Logging:
    seems that we cannot really do interesting stuff with CLI, not even save some queries via CLI, so I think we can just document about it

**Comment by ultymatom** [comment]
Error Reporting:
    https://cloud.google.com/error-reporting/docs/setup/cloud-run
    already done by default but some personalization can be needed
