### ISSUE TITLE
Block: Provision AKS environment

### ISSUE THREAD

**Issue by albertdb** [devonfw/hangar#27]
As someone setting up the project infrastructure, I want to have a detailed guide on how to provision the environment so that I can get this done fast and without errors.

Same as #10 but for Azure AKS and without the part of evaluating Rancher.

**Comment by jbellver99** [comment]
- Terraform recipes working.

- Pipeline created and working (Creates k8s cluster, storage account container & stores kubeconfig in an artifact).

**Comment by jbellver99** [comment]
PENDING:

- Store the tfstate file in the storage account container.

- Create a pipeline that uses the tfstate to destroy the k8s cluster.
