### ISSUE TITLE
Roles for CloudBuild service account to use SecretManager & Artifact Registry

### ISSUE THREAD

**Issue by lpinon** [devonfw/hangar#352]

**Comment by lpinon** [comment]
For Cloud Build: 

Artifact Registry Administrator
Artifact Registry Repository Administrator
Cloud Build Service Account
Cloud Run Admin
Secret Manager Admin
Service Account User

(needs validation)

**Comment by abcarcol** [comment]
Please, cuando pongáis un rol o permiso ponedlo en el formato "roles/[service].[role_name]" para el caso de roles y "[service].[resource].[verb]" para el caso de permisos, así puedo pasarlo directamente al script.

For Cloud Build Service Account:

roles/artifactregistry.admin
roles/artifactregistry.repoAdmin
[Cloud Build Service Account] ??
roles/run.admin
roles/secretmanager.admin
roles/iam.serviceAccountUser
