### ISSUE TITLE
Block: Prepare package/image repo

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/hangar#4]
As someone setting up the project infrastructure, I want to have a detailed guide on how to prepare a package/image repo so that I can get this done fast and without errors.

This could be either setting up the repo (hosted) or creating and configuring an account on an existing one. Briefly find out alternatives.

**Comment by sundharakanth** [comment]
Created the Pull Request with the initial draft document https://github.com/devonfw/hangar/pull/26

**Comment by sundharakanth** [comment]
**Review Comments from Albert:

Main Doc**

1. Setup DockerHub Account and Image Repo
2. Setup AWS ECR (assuming AWS Account is already available) with AWS CLI and Image Repo
3. Points about Docker Image manipulations

**Appendix**

1. Container Basics
2. All other Container Repo options in Azure, GCP, etc.

**Comment by sundharakanth** [comment]
![image](https://user-images.githubusercontent.com/91184708/152141811-8c1ef84c-e438-4165-9bbf-edf56bfcac8e.png)

**Comment by sundharakanth** [comment]
![image](https://user-images.githubusercontent.com/91184708/152142063-a6995cf4-dede-4a84-a16c-7011df6f28b9.png)

**Comment by sundharakanth** [comment]
![image](https://user-images.githubusercontent.com/91184708/156741370-4ebd9763-1e63-43ea-86aa-9b8d0b864157.png)

**Comment by sundharakanth** [comment]
![image](https://user-images.githubusercontent.com/91184708/158952417-3fcae9d9-114a-40c3-9eac-b9469629a13b.png)

**Comment by sundharakanth** [comment]
![image](https://user-images.githubusercontent.com/91184708/158952550-9acc17e1-0b08-4038-88af-fa6082f96cbc.png)
![image](https://user-images.githubusercontent.com/91184708/158952569-c3676761-b3dd-4d65-accc-d2848a5990b4.png)
