### ISSUE TITLE
Download and build image during initialize

### ISSUE THREAD

**Issue by econesag** [devonfw/hangar#442]

**Comment by airherna** [comment]
The code for this is already on the branch takeoff_develop. This task only needs to fulfill the TODOs regarding changing the image name in DockerController and uncommenting the method call that will pull the image on startup in the lib façade.

**Comment by airherna** [comment]
This is staying as a blocked task until we make sure that the image uploaded to Docker Hub correctly works with what's implemented in TakeOff
