### ISSUE TITLE
Block: Build pipeline

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/hangar#5]
As someone setting up the project infrastructure, I want to have a detailed guide on how to set up a build pipeline so that I can get this done fast and without errors.

Suggestion:
- https://github.com/devonfw-sample/devon4quarkus-reference
- https://github.com/devonfw-sample/devon4quarkus-minimal

But make it stack independent as possible.

**Comment by jbellver99** [comment]
Script for automation of generating pipelines nearly finished. Some problems need to be solved

**Comment by jbellver99** [comment]
Pending conversations for the future:

1. Taking out of the script the build part in the YAML file so the pipeline code is the same for every language.

2. Check if it is really necessary to do a git pull before executing the script.
