### ISSUE TITLE
Block: Test pipeline

### ISSUE THREAD

**Issue by SchettlerKoehler** [devonfw/hangar#6]
As someone setting up the project infrastructure, I want to have a detailed guide on how to set up a test pipeline so that I can get this done fast and without errors.

Suggestion:
- https://github.com/devonfw-sample/devon4quarkus-reference
- https://github.com/devonfw-sample/devon4quarkus-minimal

But make it stack independent as possible.

**Comment by jbellver99** [comment]
Things to take into account for the pipeline script:
1. Make it stack independent (separate pipelines from the build one).
2. The script should create a new branch where the file will be commited (feature/test-pipeline).
3. In the steps use a script to make it generic.
4. Upload the outcome into and artifact.
